# Generated by Django 5.1.4 on 2024-12-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
